"""Conversation-end detector for the voice pipeline.

Determines whether a conversation has naturally concluded by examining
both the user's farewell intent AND the assistant's closing response.

Usage
-----
    from services.conversation_end import should_end_conversation

    ended = should_end_conversation(user_message, assistant_message)
"""

from __future__ import annotations

import re


# ── User farewell phrases (multilingual) ─────────────────────────────────────
# Each entry is a compiled regex that matches the phrase as a whole word / token
# boundary so that "bye" won't match "byelaw" and "thanks" won't match
# "thanksgiving".

_USER_FAREWELL_PHRASES_EN = [
    r"\bthank\s*you\b",
    r"\bthanks\b",
    r"\bbye\s*bye\b",       # must come before bare "bye"
    r"\bbye\b",
    r"\bgoodbye\b",
    r"\bgood\s*bye\b",
    r"\bthat'?s\s+all\b",
    r"\bno\s+more\s+questions?\b",
    r"\bi'?m\s+done\b",
    r"\bsee\s+you\b",
    r"\btake\s+care\b",
    r"\bhave\s+a\s+good\s+(day|night|evening|one)\b",
    r"\bnothing\s+else\b",
    r"\bthat\s+will\s+be\s+all\b",
    r"\bi\s+don'?t\s+have\s+any\s+more\s+questions?\b",
    r"\bno\s+thanks\b",
]

_USER_FAREWELL_PHRASES_HI = [
    r"bas\s+itna\s+hi",
    r"dhanyavaad",
    r"dhanyawad",
    r"shukriya",
    r"alvida",
    r"theek\s+hai\s+bye",
    r"chalo\s+bye",
    r"aur\s+kuch\s+nahi",
    r"bas\s+ho\s+gaya",
]

_USER_FAREWELL_PHRASES_TE = [
    "ధన్యవాదాలు",
    "సరే",
    "ఇంకేమీ లేదు",
    "వీడ్కోలు",
    "బై",
    "మరి కలుద్దాం",
]

# Pre-compile English and Hindi patterns (regex)
_USER_FAREWELL_RE = [
    re.compile(pat, re.IGNORECASE)
    for pat in (_USER_FAREWELL_PHRASES_EN + _USER_FAREWELL_PHRASES_HI)
]


# ── Assistant farewell markers ───────────────────────────────────────────────
# These phrases in the assistant's reply indicate it is wrapping up the
# conversation.  We use simple substring matching here (case-insensitive)
# since the assistant output is controlled and well-formed.

_ASSISTANT_FAREWELL_MARKERS_EN = [
    "goodbye",
    "good bye",
    "bye",
    "take care",
    "feel free to reach out",
    "feel free to contact",
    "happy to help",
    "glad i could help",
    "glad to help",
    "have a great day",
    "have a good day",
    "have a nice day",
    "have a wonderful day",
    "have a good evening",
    "see you",
    "wishing you",
    "all the best",
    "best of luck",
    "talk to you later",
    "anytime you need",
    "whenever you need",
]

_ASSISTANT_FAREWELL_MARKERS_HI = [
    "अलविदा",
    "शुभकामनाएं",
    "ध्यान रखिए",
    "धन्यवाद",
    "बाय",
    "फिर मिलेंगे",
]

_ASSISTANT_FAREWELL_MARKERS_TE = [
    "వీడ్కోలు",
    "శుభాకాంక్షలు",
    "మంచి రోజు",
    "బై",
    "ధన్యవాదాలు",
    "జాగ్రత్త",
]

_ALL_ASSISTANT_MARKERS = (
    _ASSISTANT_FAREWELL_MARKERS_EN
    + _ASSISTANT_FAREWELL_MARKERS_HI
    + _ASSISTANT_FAREWELL_MARKERS_TE
)


# ── Public API ───────────────────────────────────────────────────────────────

def _user_has_farewell_intent(text: str) -> bool:
    """Return True if the user's message expresses a farewell / sign-off."""
    if not text or not text.strip():
        return False

    lowered = text.strip().lower()

    # Check compiled regex patterns (English + Hindi romanised)
    for pattern in _USER_FAREWELL_RE:
        if pattern.search(lowered):
            return True

    # Check Telugu (Unicode) — plain substring is fine here
    for phrase in _USER_FAREWELL_PHRASES_TE:
        if phrase in text:
            return True

    return False


def _assistant_is_closing(text: str) -> bool:
    """Return True if the assistant's reply sounds like a conversation closer."""
    if not text or not text.strip():
        return False

    lowered = text.strip().lower()

    for marker in _ALL_ASSISTANT_MARKERS:
        if marker.lower() in lowered:
            return True

    return False


def should_end_conversation(user_message: str, assistant_message: str) -> bool:
    """Determine whether the conversation has naturally concluded.

    Returns True ONLY when both conditions are met:
      1. The user's message carries farewell intent.
      2. The assistant's reply confirms the conversation is closing.

    This two-gate approach prevents false positives like "thanks for
    that info" (where the assistant would ask a follow-up rather than
    say goodbye).

    Parameters
    ----------
    user_message : str
        The latest user transcript (STT output or typed text).
    assistant_message : str
        The assistant's reply generated by the LLM.

    Returns
    -------
    bool
        True if the conversation should be terminated.
    """
    return _user_has_farewell_intent(user_message) and _assistant_is_closing(assistant_message)
